### ISSUE TITLE
Assignment 1: Expense ID - Integer or String

### ISSUE THREAD

**Issue by udayskyport** [sithu/cmpe273-fall16#2]
@sithu 
Dear Professor,
The 'Expense ID' as mentioned in POST response is String.
Do we have to return it as String - (We may have to change the datatype if DB uses Integer)?
Similarly for 'Expense Amount'.

@nagkumar91 
 if we return ID as String, In the test script line 115 - It tries to add Integer and string (from response) and causes failure.

Can you please advice the response datatype for such cases?

**Comment by nagkumar91** [comment]
@udayskyport I have updated the script. Hope this handles the situation.
Data type for ID is your choice. The spec says that its a string. 
Thank you for pointing this out. Please let me know if this works.
